// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  button: string;
  imageContainer: string;
  intro: string;
  introbuttons: string;
  landing: string;
  text: string;
}
export const cssExports: CssExports;
export default cssExports;
