// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Landing': string;
  'button': string;
  'intro': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
