// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'postQuestionButton': string;
  'postQuestionContainer': string;
  'questionForm': string;
  'questionInput': string;
  'questionLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
