// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  hiddenID: string;
  loading: string;
  modalButtonStyle: string;
  modalDivStyle: string;
  modalTextAreaStyle: string;
  questionItem: string;
  questionList: string;
  questionListContainer: string;
  questionText: string;
  questionTitle: string;
  questionsHeader: string;
}
export const cssExports: CssExports;
export default cssExports;
