// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loading': string;
  'questionItem': string;
  'questionList': string;
  'questionListContainer': string;
  'questionText': string;
  'questionTitle': string;
  'questionsHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
