// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loading': string;
  'question-item': string;
  'question-list': string;
  'question-text': string;
  'question-title': string;
  'questions': string;
  'questions-header': string;
}
export const cssExports: CssExports;
export default cssExports;
