// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'answerButton': string;
  'answerItem': string;
  'hiddenID': string;
  'loading': string;
  'modalButtonStyle': string;
  'modalDivStyle': string;
  'modalTextAreaStyle': string;
  'questionItem': string;
  'questionList': string;
  'questionListContainer': string;
  'questionText': string;
  'questionsHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
