const DISPLAY_ALERT = 'DISPLAY_ALERT';
const REMOVE_ALERT = 'REMOVE_ALERT';

const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN';
const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

const LOGOUT_USER = 'LOGOUT_USER';

const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

const HANDLE_CHANGE = 'HANDLE_CHANGE';

export {
  DISPLAY_ALERT,
  REMOVE_ALERT,
  REGISTER_USER_BEGIN,
  REGISTER_USER_SUCCESS,
  REGISTER_USER_ERROR,
  LOGIN_USER_BEGIN,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_ERROR,
  LOGOUT_USER,
  GET_CURRENT_USER_BEGIN,
  GET_CURRENT_USER_SUCCESS,
  HANDLE_CHANGE,
};
